apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: app-dev
  namespace: flux-system
spec:
  dependsOn:
    - name: flux-system
  interval: 1m
  path: ./overlays/development
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  targetNamespace: development
